New introduction to tables
oetiker/lshort pull request #37
Opened 2022-05-12 07:45 UTC by marcin-serwin

This PR rewrites the introduction on tables to be more focused on `booktabs` package and adds examples of using the `longtable` and `array` packages. Tables throughout the document were also improved by adding to them uniform headers.

2022-05-12 08:00 UTC, oetiker commented
wow ... you are incredible! love all the new content ... will get to reviewing this in a bit ... as I said, how about becoming a co-author, billed on the frontpage ?

2022-05-12 08:15 UTC, marcin-serwin commented
> how about becoming a co-author, billed on the frontpage ?

Thank you for the offer. I'll add myself in a minute.

2022-05-12 15:04 UTC, oetiker requested changes

2022-05-12 15:04 UTC, oetiker commented on book/src/realworld.tex
> +When a certain column must be formatted a certain way it is inconvenient to put
```suggestion
When a column must be formatted a certain way it is inconvenient to put
```

2022-05-14 15:16 UTC, oetiker approved these changes

2022-05-14 15:16 UTC, merged