Rewrite `fancyhdr` tutorial
oetiker/lshort pull request #40
Opened 2022-05-14 17:18 UTC by marcin-serwin

This PR considerably expands the `fancyhdr` tutorial.

2022-05-16 07:57 UTC, oetiker requested changes

2022-05-16 07:57 UTC, oetiker commented on book/src/basics.tex
> +You may also control the style of the displayed page numbers. To change it use
```suggestion
You can also control the style of the displayed page numbers. To change the style use
```

2022-05-16 07:57 UTC, oetiker commented on book/src/basics.tex
> +command, where \carg{style} is one of the styles presented in
```suggestion
command, where \carg{style} is one of the styles listed in
```

2022-05-16 07:57 UTC, oetiker commented on book/src/spec.tex
> +additional page style \cargv{fancy} that can be customised to our liking. By
```suggestion
additional page style \cargv{fancy} and a set of commands to customise it to our liking. By
```

2022-05-16 07:57 UTC, oetiker commented on book/src/spec.tex
> +default it only adds a line separating header from the page body.
```suggestion
default it only adds a line separating the header from the page body.
```

2022-05-16 07:57 UTC, oetiker commented on book/src/spec.tex
> +The basic command of the package is
```suggestion
The primary command of the package is
```

2022-05-16 07:57 UTC, oetiker commented on book/src/spec.tex
> +argument. There are total of 12 different places and each is identified by a
```suggestion
The \carg{places} is a comma separated list of places where the \carg{field} should be displayed. There are total of 12 different places and each is identified by a
```

2022-05-16 07:57 UTC, oetiker commented on book/src/spec.tex
> +  \item The first letter tells whether it is in a header (\cargv{H}) or in a
```suggestion
  \item The first specifies whether the location is in the header (\cargv{H}) or in the
```

2022-05-16 07:57 UTC, oetiker commented on book/src/spec.tex
> +  right (\cargv{R}).
```suggestion
  \item The second letter specifies the location within the header\slash footer: (\cargv{L}) for left, (\cargv{C}) for center and
 (\cargv{R}) for right.
```

2022-05-16 07:57 UTC, oetiker commented on book/src/spec.tex
> +  all pages are treated as odd.
```suggestion
  \item The third letter defines whether the field should be printed on even
  (\cargv{E}) or odd (\cargv{O}) pages. If the document is not two sided then
  all pages are treated as odd.
```

2022-05-16 07:57 UTC, oetiker commented on book/src/spec.tex
> +\cargv{HR} means right part of the header on both odd and even pages.
```suggestion
\cargv{HR} is right side of the header on both odd and even pages.
```

2022-05-16 07:57 UTC, oetiker commented on book/src/spec.tex
> +their \carg{places} argument if it's missing.
```suggestion
their \carg{places} argument unless specified differently.
```

2022-05-16 07:57 UTC, oetiker commented on book/src/spec.tex
> +the same way except that they imply respectively \cargv{H} and \cargv{F} in
```suggestion
the same way except that they assume \cargv{H} and \cargv{F} respectively
```

2022-05-16 07:57 UTC, oetiker commented on book/src/spec.tex
> +macros to the desired length.
```suggestion
macros to the desired width.
```

2022-05-16 07:57 UTC, oetiker commented on book/src/spec.tex
> +of \pai*{fancyhdr}.}
```suggestion
terminology. Before we talk about the default ones let's consider how you can
define your own using the \pai{extramarks}\footnote{\pai{extramarks} is part
of \pai*{fancyhdr}.} package.
```

2022-05-16 07:57 UTC, oetiker commented on book/src/spec.tex
> +The \ci{extramarks} is used to set the contents of \carg{left} and \carg{right}
```suggestion
The \ci{extramarks} command is used to set the contents of \carg{left} and \carg{right}
```

2022-05-16 07:57 UTC, oetiker commented on book/src/spec.tex
> +marks. Then you can access those inside the headers by using the appropriate
```suggestion
marks. Then you can access these marks inside the headers by using the appropriate
```

2022-05-16 07:57 UTC, oetiker commented on book/src/spec.tex
> +marks. To disable this use the \ci{nouppercase} command inside the \ci{fancyhf}
```suggestion
You may have noticed that section titles are typeset in uppercase when provided by
marks commands. To disable this use the \ci{nouppercase} command inside the \ci{fancyhf}
```

2022-05-16 07:57 UTC, oetiker commented on book/src/spec.tex
> +available.
```suggestion
If you only want to change the right mark, use the \ci{markright} command.
```

2022-05-16 07:57 UTC, oetiker commented on book/src/spec.tex
> +By default the field in the centre of header\slash footer will expand equally
```suggestion
By default the field in the centre of the header\slash footer will expand equally
```

2022-05-16 07:58 UTC, oetiker commented
great! don't forget the Changes file!

2022-05-17 07:28 UTC, oetiker approved these changes

2022-05-17 07:29 UTC, merged

2022-05-17 07:29 UTC, oetiker commented
thank you! any more plans ?

2022-05-17 07:56 UTC, marcin-serwin commented
I'm currently working on integrating `chktex` and `latexindent` into github actions workflow. After that I planned to rework the `realworld` and `intro` to better introduce what logical markup is. After that maybe update `fontspec` and change the layout a bit so that a4, a5 and letter versions use the same text width (fewer problems with `overfull hbox`es).

2022-05-17 08:04 UTC, oetiker commented
Great :) looking forward to your PRs. What is motivating you to all this effort?

2022-05-17 09:17 UTC, marcin-serwin commented
> What is motivating you to all this effort?

I don't know, it's just fun :>