Intro overhaul
oetiker/lshort pull request #42
Opened 2022-05-22 17:17 UTC by marcin-serwin

This PR updates the first and second chapter by reshuffling and expanding on some concepts. It also introduces new section on logical document markup and new appendix detailing deprecated `LaTeX` syntax.

2022-05-23 06:47 UTC, oetiker commented
re the poliglossia fix ... even once it is merged, this will take time to appear in real life LaTeX setups ... can you fix is for this document? so that it will at least compile on tl2022

2022-05-23 08:52 UTC, oetiker requested changes
some input :)

2022-05-23 08:52 UTC, oetiker commented on book/src/basics.tex
> +references right. When your input file has a bug \LaTeX{} will tell you about
```suggestion
references right. When your input file has a bug, \LaTeX{} will tell you about
```

2022-05-23 08:52 UTC, oetiker commented on book/src/basics.tex
> +this idea in more detail by presenting a problem and showing how it can be
```suggestion
this idea in more detail by presenting a problem and demonstrating how it can be
```

2022-05-23 08:52 UTC, oetiker commented on book/src/basics.tex
> +\carg{text} it received as a parameter.
```suggestion
It stands for \enquote{emphasise} and does just that: it emphasises the
\carg{text} it received as a parameter.
```

2022-05-23 08:52 UTC, oetiker commented on book/src/basics.tex
> +code from a file into your document, you need to enhance the capabilities of
oh yea ... a section on the listings package would be nice too :)

2022-05-23 08:52 UTC, oetiker commented on book/src/basics.tex
> +to its entry in our bibliography. Along other information you can also check
```suggestion
to its entry in our bibliography. In the bibliograph entry you will also find information about the package
```

2022-05-23 08:52 UTC, oetiker commented on book/src/basics.tex
> +the version that was used when describing it. You can check the versions of
```suggestion
version that was used when writing this booklet. You can check the versions of
```

2022-05-23 08:52 UTC, oetiker commented on book/src/basics.tex
> +used packages in the \eei{.log} file that is produced when compiling a document
```suggestion
all the packages used in a document, by looking at the \eei{.log} file that is produced when compiling the document.
```

2022-05-23 08:52 UTC, oetiker commented on book/src/basics.tex
> +that uses the package. If they aren't very different (usually the first number
```suggestion
If the package versions aren't very different (usually the first number
```

2022-05-23 08:52 UTC, oetiker commented on book/src/basics.tex
```suggestion

\pai*{fancyhdr}     & Let's you easily customize page headers and footers. Described in Section~\ref{sec:fancy}.\\
```

2022-05-23 08:52 UTC, oetiker commented on book/src/deprecated.tex
> +\chapter{Things You Shouldn't Use}
```suggestion
\chapter{Things You Shouldn't Use}

\begin{intro}
  \LaTeX{} has been around for well over 30 years now. And it has remained largly backward compatible. This means
  you can scrib use text and tricks from a friends document written ten years ago and use them in your document today.
  In many intances this is totally fine, in others, while \LaTeX{} works fine with the old code, you still should not do it. 
  Have a look!
\end{intro}

```

2022-05-23 08:52 UTC, oetiker commented on book/src/deprecated.tex
> +from ideal. Therefore it is recommended to always use \ei{align} environments
```suggestion
from ideal. Therefore it is recommended to always use the \ei{align} environments
```

2022-05-24 07:54 UTC, oetiker commented on book/src/deprecated.tex
> +\section{Adding Bibliography}
```suggestion
\section{Adding a Bibliography}
```

2022-05-24 07:54 UTC, oetiker commented on book/src/deprecated.tex
> +\ei{verbatim} (from \pai(verbatim) package)
```suggestion
\ei{verbatim} (from the \pai(verbatim) package)
```

2022-05-24 07:55 UTC, oetiker commented on book/src/deprecated.tex
> +\LaTeX{} defines its own \ei{verbatim} environment, however there are problems
```suggestion
\LaTeX{} comes with a \ei{verbatim} environment built into the core, however there are problems
```

2022-05-24 07:58 UTC, oetiker commented on book/src/realworld.tex
> +not use groups for getting its first argument. Instead you pass it between a
```suggestion
not use groups for getting its first argument. Instead you pass the argument between a
```

2022-05-24 07:58 UTC, oetiker commented on book/src/realworld.tex
> +chosen delimiters that can be any character except for letters, \verb|*| or
```suggestion
chosen delimiters that can be any character except a letter, \verb|*| or
```

2022-05-24 08:00 UTC, oetiker commented on book/src/realworld.tex
> +Text that is enclosed between these delimiters will be directly printed, as if
```suggestion
Text that is enclosed between these delimiters will be printed without \LaTeX{} reacting to any special charaters or macros. The outpup will use the typewriter font.
```

2022-05-24 08:09 UTC, oetiker commented on book/src/realworld.tex
> +Due to the fact that the \pai{minted} package relies on third party program
```suggestion
Due to the fact that the \pai{minted} package relies on an external program
```

2022-05-24 08:10 UTC, oetiker commented on book/src/realworld.tex
> +point actually means. It allows the \LaTeX{} document to call any program via
```suggestion
point actually means. It allows the \LaTeX{} document to call any external program via
```

2022-05-24 08:10 UTC, oetiker commented on book/src/realworld.tex
> +shell. Let me repeat this to make the point clear: \emph{Enabling this flag
```suggestion
the shell. Let me repeat this to make the point clear: \emph{Enabling this flag
```

2022-05-24 08:10 UTC, oetiker commented on book/src/realworld.tex
> +  allows the \LaTeX{} document to call any program via shell}. This means that
```suggestion
  allows the \LaTeX{} document to call any program via the shell}. This means that
```

2022-05-24 08:12 UTC, oetiker commented on book/src/realworld.tex
> +include you can use \ci{setminted} to define the default values.
```suggestion
include, you can use \ci{setminted} to define the default values.
```

2022-05-24 09:04 UTC, oetiker commented
great the minted code snippets ... the small `\end{xxx}` look a bit odd in my eyes ...

2022-05-24 09:05 UTC, oetiker commented on book/src/deprecated.tex
> +  largely backward compatible. This means you can use text and tricks from
```suggestion
  largely backward compatible. This means you can easily steal snipptes from
```

2022-05-24 09:07 UTC, oetiker commented on book/src/deprecated.tex
> +  In many instances this is totally fine, in others, while \LaTeX{} works fine
```suggestion
  In many instances this work without any problem. But eventhough \LaTeX{} seems happy
```

2022-05-24 13:33 UTC, merged

2022-05-27 07:19 UTC, oetiker commented
about the outdent ... 

the "problem" is that we have a single column layout where we should not be using more than 66 chars wide text for easy readability, and a two column layout for the examples, we every bit of extra horizontal space is needed as we can see already now by the fact that you have started doing examples where you use different widths for the rendered content ...

Instead of getting rid of the outdent, I would rather try to make the examples appear more as a unit, which may be achieved by adding extra space ... 

Having an alternate layout for cases where the source and output do not fit side by side, or also where the source is much longer than the output, seems like a sensible approach ... 

I was also wondering if we maybe should move the examples into floating objects ... especially for long ones, this would simpyfy the layout as well.

2022-05-27 09:01 UTC, marcin-serwin commented
> Instead of getting rid of the outdent, I would rather try to make the examples appear more as a unit, which may be achieved by adding extra space ...

I was thinking about doing both. Since we are already accepting alternate layouts for different cases I think we can just drop the old solution of extending space for all the examples. If the examples are small, this is just wasted space and if they are big we can typeset them as code over output. 

> I was also wondering if we maybe should move the examples into floating objects ... especially for long ones, this would simpyfy the layout as well.

Floating smaller examples is not very useful and some of the bigger ones are already floated. Maybe we should just do it with more of the big examples. But I don't think that they should get their own table of figures at the beginning, since they are not special, just big.

2022-05-27 13:14 UTC, oetiker commented
sounds like a plan :) looking forward to your PR

If you can make it so that the columns between output and input is always in the same place, this would probably also help with makeing the layout more quiet.